# Generated by Django 3.0.6 on 2020-05-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoorPromo',
            fields=[
                ('psid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('qr_imgage_code', models.CharField(max_length=120)),
                ('status', models.BooleanField(default=False)),
                ('source', models.CharField(max_length=120)),
                ('promo_id', models.CharField(max_length=50)),
                ('name', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
