# Generated by Django 3.0.6 on 2020-05-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promomodels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doorpromo',
            old_name='qr_imgage_code',
            new_name='qr_image_code',
        ),
    ]
