# Generated by Django 3.0.6 on 2020-05-05 18:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('promomodels', '0002_auto_20200505_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('psid', models.BigIntegerField()),
                ('order_amount', models.FloatField()),
                ('promo_id', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
