# Generated by Django 3.0.6 on 2020-05-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promomodels', '0003_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='id',
            new_name='_id',
        ),
    ]
