# Generated by Django 3.0.6 on 2020-05-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promomodels', '0005_auto_20200505_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='date_time',
            new_name='date',
        ),
    ]
