# Generated by Django 3.0.6 on 2020-05-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promomodels', '0006_auto_20200505_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doorpromo',
            name='qr_image_code',
        ),
    ]
